language: csharp
os: linux
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - dotnet restore
    - dotnet build
    - cd tests/Generic.Repository.Test
    - dotnet test
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

# You must run this command to give Travis permissions to execute the build.sh shell script:
# git update-index --chmod=+x build.sh
script:
    - ./build.sh
