version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2 
  branches:
      ignore:
        - develop
        - /feature-.*/
   steps:
     - checkout
     - run:
         name: Build
         command: 
            ./build.sh
