
name: ASP.NET Core CI

on: 
  push:
  - master
  - develop

jobs:
  test:
    name: Test on OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        core_version: [2.2]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      run: ./build.sh
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
