
name: ASP.NET Core CI

on:
  push:
    branches:
    - master
    - develop
    tags:
    - '*.*.*'
  pull_request:
jobs:
  build:  
    strategy:
      matrix:
        core_version: [2.2.108]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    name: Test on net core ${{ matrix.core_version }} and ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - run: dotnet --info
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
    - if: !contains(matrix.os, 'windows-latest')
      run: ./build.sh
   - if: contains(matrix.os, 'windows-latest')
      run: ./build.ps1
