
name: ASP.NET Core CI

on:
  push:
    branches:
    - master
    - develop
    tags:
    - '*.*.*'
  pull_request:
jobs:
  build:  
    strategy:
      matrix:
        core_version: [2.2.108]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    name: Test on net core ${{ matrix.core_version }} and ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v1
      - with:
          version: ${{ matrix.core_version }}
      - run: ./build.sh
