
name: ASP.NET Core CI

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:
    name: Test on OS ${{ matrix.os }} - .Net Core Version: ${{ matrix.core_version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        core_version: [2.2.108]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      run: ./build.sh
